export const domain = 'http://movie0706.cybersoft.edu.vn'
export const groupID_carousel = 'GP06'
export const groupID_defaultTab = 'GP05'
export const groupID_Tab2 = 'GP07'
export const groupID_Tab3 = 'GP09'